[gcp_service_account]
type = "service_account"
project_id = "automated-email-441320"
private_key_id = "a6f53b40c7229f4acd531ec0a8dfa3b582b0ce45"
private_key = '''-----BEGIN PRIVATE KEY-----
MIIEvwIBADANBgkqhkiG9w0BAQEFAASCBKkwggSlAgEAAoIBAQCekgBXA9KC4/I+
bCpAG1JGx8TQe4zheNHjGzdrV30KuXSRJ8LvDN/dyiCwyHjPYYym9iTBE0K22HoW
DFsoxjhbpKSbIxCbNKsyuqitUUVGhZ0gc0CyA0+MGIweR7XUBmEEGMqVAh1NhqHX
J9Xggz5wVcoKF4JeVVyTgCBBfcD2f0gS8H7ZtcE2ycqXy0HqpskUzhwTiYZe+ivF
rnXoMjrIz3+l6nkxFq2rnm65LWHbPWano/KSC4Q8eAlOI7Z4ubyWu9nhU8Ab6pnA
utQ9icrwF6iHyX9P7VqH17GBdzS9MDibcDcpOJUEIolAtL2gn7YhEKV5l3fk9/Cs
RQqAYD6HAgMBAAECggEAGZT6Yw9lzeISecmfg1olCvA9q1jTYKjKS7ZfWXzy2mET
Ejv08fYEw9ZRMdQV0XcuZt09Dr0ZvT/talMx/cEE5JwKRlEA49k6aWO9xMBgycDS
maKeZFmuYq6vJE9zYTJqQmvxetqteY1n3Ls7gQ4La7obb0ddq/RfjBhWm9o64Ell
g2tsv0yjbXeEq0aPW6Z5fBclYZJg44RtmN+ZnI4mOVjmWsAhczxxezlU+a54ioQD
6ZZYhhry6+bo/V13kmPVakC90UHlcbOWO4PJOCYvd6uDkPi05XK6Je9NTuHVeb8p
Agznx17FFsfj9PNHOM7NhGn+WdJ7tYvrm0yepXmi0QKBgQDOJpgvDj1lJWq1JxhP
6qcQTa9jcP5h+OH+767Piv2a60XZusMNPz9pa0OfKH/31IhfcBmHzurNYMsFS0Li
jx9qdFJWP/sezJq8jzvJfgmg29UBHT3V3TbMMbdw/kbc32lDyM0H7nPJquQZQdiS
cmZXK2w7goUVnwbf1+YcwDEW+QKBgQDE6gWlUgjXyrIzzs7Sqe1XVSLNPygTxGtL
Via3n7kxozTc3Y8YYMkiHqGOJG+qpmZsdaPKBydfQq4uNQkksHODQn12s2Q8NSle
GU6yIaYXMmGdvlzvTDli9KKVJ8Iw/bK+p3G45VVVIRhn419+ZbHSIjrBeVb3IbRQ
BOlgtb3hfwKBgQCqUDhqp9kRN1hxUVtEqxha39OG1FNVnckYVeyWir36v2V1/FYp
G5fIAFZdp5gRqAUC1BpDmS9jfhQ8y3D2vEe4K2Ha4AEX8PHl1nAOh5Js0zGnOgFc
LuaWzHxBXdItqGXPGpZJdzcx5X2NYFkMpHbojXddsvdAZaHITRZPqnjkAQKBgQC+
NfjiKw4TtN7SoLC0WiTDuZ92d8102sVx7nRT59vykN6dgv+Y4tUnOkOAlL2xMC+8
ER74JlTn9fde9ygv4qqSXoXnRX5Lkma1WOjltQ9FVQtqXtpS5WSBrCHoxpEU1dv1
wrVdj1oQc3mp0L8Lz5wniZ0MCvPwoQQWT8hH/QbAbQKBgQCUmez6Vi3d86kgxS5K
Dwn/Ozr/X2lnZqJm+eQksr8uJ0K5K5o9VZyVlX2mZ7UrZOfMvan8fI6CSk6kNRLw
+lHMZ4OwY4Ibdzaw9rimfQoVN0qCd0a7T9NHZ8hYuZ8hL88vfKwFLo5QzdTXTQQV
aiDt4tY8TDPLd6ILRdt/UxCkCA==
-----END PRIVATE KEY-----'''
client_email = "automated-email@automated-email-441320.iam.gserviceaccount.com"
client_id = "106725310837809169019"
auth_uri = "https://accounts.google.com/o/oauth2/auth"
token_uri = "https://oauth2.googleapis.com/token"
auth_provider_x509_cert_url = "https://www.googleapis.com/oauth2/v1/certs"
client_x509_cert_url = "https://www.googleapis.com/robot/v1/metadata/x509/automated-email%40automated-email-441320.iam.gserviceaccount.com"
universe_domain = "googleapis.com"